# Generated by Django 6.1.1 on 2026-09-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testspec',
            name='login_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='login_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='login_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='password_selector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='requires_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testspec',
            name='submit_selector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='username_selector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
